language: php

php:
  - 5.6
  - 7.0
  - 7.1

services:
  - postgresql

before_install:
  - sudo apt-get update > /dev/null
  - sudo apt-get install apache2 -y
  - composer self-update
  - composer global require drush/drush:8
  - sudo apt-get install -y -qq postfix
install:
  # setup fake mailserver
  - sudo service postfix stop
  - smtp-sink -d "%d.%H.%M.%S" 127.0.0.1:2500 1000 &
  - echo -e '#!/usr/bin/env bash\nexit 0' | sudo tee /usr/sbin/sendmail
  - echo 'sendmail_path = "/usr/sbin/sendmail -t -i "' | sudo tee "/home/travis/.phpenv/versions/`php -i | grep "PHP Version" | head -n 1 | grep -o -P '\d+\.\d+\.\d+.*'`/etc/conf.d/sendmail.ini"
  - export PATH="$HOME/.config/composer/vendor/bin:$PATH"
  - export DRUPAL_ROOT="$HOME/build/$TRAVIS_REPO_SLUG/drupal-7.56"
  - psql -c "create user drupal with password 'drupal';" -U postgres
  - psql -c "create database drupal with owner drupal;" -U postgres
  - wget https://ftp.drupal.org/files/projects/drupal-7.56.tar.gz
  - tar xvzf drupal-7.56.tar.gz
  - cd $DRUPAL_ROOT
  - drush --verbose site-install --db-url=pgsql://drupal:drupal@127.0.0.1/drupal --db-su='drupal' --db-su-pw='drupal' --yes
  - wget --no-check-certificate https://drupal.org/files/drupal.pgsql-bytea.27.patch
  - patch -p1 < drupal.pgsql-bytea.27.patch
  - cd $DRUPAL_ROOT/sites/all/modules
  - git clone https://github.com/isumoc/brilliant_gallery_pgsql.git
  - drush pm-enable brilliant_gallery -y
  - drush cc all --yes
  - drush status

before_script:
  - drush runserver 127.0.0.1:8080 &

script: /bin/true
